name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Project Dependencies
        run: uv sync --frozen --group dev

      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          pre-commit run --all-files --show-diff-on-failure

  test:
    name: Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.event.pull_request.base.repo.full_name || github.repository }}"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          lfs: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Project Dependencies
        run: uv sync --frozen --group dev --all-extras

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --no-save-images
